class CreateAgents < ActiveRecord::Migration[5.0]
  def change
    create_table :agents do |t|
      t.string :admin_id
      t.string :agency_name
      t.string :accounting_name
      t.string :first_name
      t.string :middle_name
      t.string :last_name
      t.string :agent_type
      t.string :section_name
      t.string :credit_limit
      t.string :credit_value
      t.string :credit_usage
      t.string :credit_distribution
      t.string :opening_balance
      t.string :lead_time
      t.string :address
      t.string :city
      t.string :pincode
      t.string :country
      t.string :time_zone_offset
      t.string :enable_dst
      t.string :phone
      t.string :mobile
      t.string :fax
      t.string :email
      t.string :username
      t.string :password
      t.string :designation
      t.string :nature_of_business
      t.string :logo
      t.string :currency
      t.string :credit_option
      t.string :no_of_days
      t.string :status
      t.string :create_date
      t.string :modify_date
      t.string :parent_agent
      t.string :debug
      t.string :can_book
      t.string :can_voucher
      t.string :markup
      t.string :branch_id
      t.string :consultant_id
      t.string :sales_manager_id
      t.string :is_super_user
      t.string :block_mail
      t.string :allow_book_under_cancellation
      t.string :updateflag
      t.string :created_by
      t.string :website
      t.string :ukey
      t.string :profile
      t.string :account_email
      t.string :send_sms
      t.string :acc_name
      t.string :acc_email
      t.string :acc_phone
      t.string :man_name
      t.string :man_email
      t.string :man_phone
      t.string :res_name
      t.string :res_email
      t.string :res_phone
      t.string :agency_email
      t.string :payment_type
      t.string :remarks
      t.string :accounts_processed
      t.string :site_id
      t.string :wh_agent
      t.string :wh_main_agent
      t.string :last_login_date
      t.string :apply_service_tax
      t.string :allow_quotation
      t.string :is_xmlout
      t.string :ip_address
    end
  end
end
